services:
  backend:
    image: amazoncorretto:17-alpine
    container_name: dagachi_be
    ports:
      - "3000"
    volumes:
      - ./backend/app.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    networks:
      - dagachi-network
    restart: always

  frontend:
    image: nginx:stable-alpine
    container_name: dagachi_fe
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - certbot_data:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - dagachi-network
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - ./nginx/certbot/logs:/var/log/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: > 
      certonly --webroot --webroot-path /var/www/certbot/ 
      --email gwtt0878@gmail.com --agree-tos --no-eff-email
      -d dagachi.gwtt.site
    networks:
      - dagachi-network
    depends_on:
      frontend:
        condition: service_healthy
    restart: always

networks:
  dagachi-network:
    driver: bridge

volumes:
  certbot_data:
    driver: local