services:
    database:
        image: mysql:8.4
        container_name: dagachi_db
        env_file:
            - ./.env.mysql
        volumes:
            - mysql_data:/var/lib/mysql
            - ./dagachi_db/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - app-network
        ports:
            - 3306:3306
        command: >
            bash -c "
            chmod 644 /etc/mysql/conf.d/my.cnf && mysqld
            "
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
    
    backend:
        build:
            context: ./dagachi_be
            dockerfile: Dockerfile
        container_name: dagachi_be
        env_file:
            - ./.env.be
        depends_on:
            database:
                condition: service_healthy
        networks:
            - app-network
        ports:
            - 3000:3000
    frontend:
        build:
            context: ./dagachi_fe
            dockerfile: Dockerfile
        container_name: dagachi_fe
        ports:
            - 8080:80
        depends_on:
            - backend
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    mysql_data: