services:
  backend:
    image: amazoncorretto:17-alpine
    container_name: dagachi_be
    ports:
      - "3000:3000"
    volumes:
      - ./dagachi/backend/app.jar:/app/app.jar
    command: ["java", "-jar", "app.jar"]
    restart: always
    networks:
      - dagachi-network

  frontend:
    image: nginx:stable-alpine
    container_name: dagachi_fe
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dagachi/nginx/html:/usr/share/nginx/html
    networks:
      - dagachi-network

networks:
  dagachi-network:
    driver: bridge