# spring:
#   timezone: Asia/Seoul
#   application:
#     name: dagachi
#   datasource:
#     url: 
#     username: 
#     password: 
#     driver-class-name: 
#   jpa:
#     hibernate:
#       ddl-auto: 
#     show-sql: 
#     properties:
#       hibernate:
#         format_sql: 
#   data:
#     redis:
#       host: ${REDIS_HOST}
#       port: 6379
#       timeout: 2000
#       lettuce:
#         pool:
#           max-active: 8
#           max-idle: 8
#           min-idle: 0
        
# server:
#   port: 

# cors:
#   allowed-origins: 

# jwt:
#   secret-key: 
#   expiration-time: 

spring: 
  profiles:
    active: dev