# spring:
#   timezone: Asia/Seoul
#   application:
#     name: dagachi
#   datasource:
#     url: 
#     username: 
#     password: 
#     driver-class-name: 
#   jpa:
#     hibernate:
#       ddl-auto: 
#     show-sql: 
#     properties:
#       hibernate:
#         format_sql: 
        
# server:
#   port: 

# cors:
#   allowed-origins: 

# jwt:
#   secret-key: 
#   expiration-time: 

spring: 
  profiles:
    active: dev