name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - production
    paths:
        - 'dagachi_be/**'
        - '.github/workflows/be.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      
      - name: Create backend application.yml
        run: |
          mkdir -p dagachi_be/src/main/resources
          echo "${{ secrets.BACKEND_APP_YML }}" > dagachi_be/src/main/resources/application-prod.yaml

      - name: chmod +x gradlew
        run: cd dagachi_be && chmod +x ./gradlew

      - name: Build with Gradle
        run: cd dagachi_be && ./gradlew build -x test

      - name: rename jar
        run: cd dagachi_be/build/libs && mv *.jar app.jar

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dagachi_be/build/libs/app.jar,docker-compose.prod.yml"
          target: "/home/ubuntu/dagachi/backend/app.jar,docker-compose.prod.yml"

      - name: SSH and restart Spring Boot app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker compose -f docker-compose.prod.yml restart backend